import { useState, type FormEvent } from 'react';
import type { ProjectInput } from './types';
import { FilePicker } from './FilePicker';
export function validateInput(input: ProjectInput, fileCount: number): string | null {
  if (!input.seedName.trim()) return 'Add a starting person or family name.';
  if (!input.geography.trim() && !input.geographyUnknown) return 'Add a family location or choose “I do not know.”';
  if (!input.context.trim() && !input.preparedPacket && !fileCount) return 'Add a file, a family memory or a prepared packet.';
  return null;
}
export function InputScreen({onStart, busy, error}: {onStart:(input:ProjectInput,files:File[])=>void;busy:boolean;error:string|null}) {
  const [input,setInput]=useState<ProjectInput>({seedName:'',geography:'',geographyUnknown:false,context:'',preparedPacket:false,language:'en',aliases:[]});
  const [files,setFiles]=useState<File[]>([]);
  const [validation,setValidation]=useState<string|null>(null);
  const field = (key: keyof ProjectInput, value: string | boolean) => setInput(current=>({...current,[key]:key==='aliases'?String(value).split(',').map(s=>s.trim()).filter(Boolean):value}));
  const submit=(e:FormEvent)=>{e.preventDefault();const issue=validateInput(input,files.length);setValidation(issue);if(!issue)onStart(input,files)};
  return <main className="input-screen"><div className="intro"><span className="eyebrow">A little evidence. A lasting connection.</span><h1>Your family story,<br/><em>coming together.</em></h1><p>Start with a name, a photograph, a memory.<br/>Keep the stories — and the sources behind them.</p></div>
    <form className="intake" onSubmit={submit} noValidate><section className="intake-material"><span className="step-label">01 / Bring what you have</span><FilePicker files={files} onChange={setFiles} disabled={busy}/><label className="field">A memory or a little context<textarea value={input.context} onChange={e=>field('context',e.target.value)} placeholder="My grandfather often spoke about…" rows={3}/></label><label className="check"><input type="checkbox" checked={input.preparedPacket} onChange={e=>field('preparedPacket',e.target.checked)}/>Use the configured prepared family packet</label><small className="muted">Existing family records will be labeled as an import.</small><div className="connections"><span className="eyebrow">Optional connections</span><div><button type="button" disabled>Google Drive · unavailable</button><button type="button" disabled>Email · unavailable</button></div></div></section>
    <section className="intake-details"><span className="step-label">02 / Where should we begin?</span><label className="field">Starting person or family name <span aria-hidden="true">*</span><input autoComplete="off" value={input.seedName} onChange={e=>field('seedName',e.target.value)} placeholder="A full name or family name" aria-required="true"/></label><label className="field">Family geography<input value={input.geography} disabled={input.geographyUnknown} onChange={e=>field('geography',e.target.value)} placeholder="A village, region or country" aria-required={!input.geographyUnknown}/></label><label className="check"><input type="checkbox" checked={input.geographyUnknown} onChange={e=>field('geographyUnknown',e.target.checked)}/>I do not know the family location</label>
    <details className="optional"><summary>A few more details <span>optional</span></summary>{([['birthPlace','Birthplace'],['currentPlace','Current place'],['period','Approximate years'],['aliases','Other names or spellings']] as const).map(([key,label])=><label className="field" key={key}>{label}<input value={key==='aliases'?input.aliases.join(', '):input[key]||''} onChange={e=>field(key,e.target.value)}/></label>)}<label className="field">Book language<select value={input.language} onChange={e=>field('language',e.target.value)}><option value="en">English</option></select></label></details>
    {(validation||error)&&<p role="alert" className="error">{validation||error}</p>}<button className="primary start-button" disabled={busy}>{busy?<><span className="spinner"/>Reading your material…</>:<>Start the search <span aria-hidden="true">↗</span></>}</button><p className="fine-print">You stay part of the story. Review suggestions,<br/>keep unknowns open, and add more at any time.</p></section></form><p className="input-footer">Family memories stay distinct from archival evidence.</p></main>;
}
