import { useState } from "react";
import type { BankAnswerInput, BankQuestion, GraphProposalReview, ProjectSnapshot } from "../../packages/contracts";
export function QuestionBank({snapshot, busy, onAnswer, onReview, onSource}: {snapshot: ProjectSnapshot; busy: boolean; onAnswer?: (input: BankAnswerInput) => Promise<boolean>; onReview?: (input: GraphProposalReview) => Promise<boolean>; onSource: (id: string) => void}) {
  const [showSaved, setShowSaved] = useState(false);
  const research = snapshot.research!;
  const questions = research.questionBank.filter(q => showSaved || q.status === "open");
  return <section className="question-bank" aria-label="Research question bank"><h3>Research questions</h3><p>Keep useful questions for later. Your initial checks stay saved.</p><label className="check"><input type="checkbox" checked={showSaved} onChange={e => setShowSaved(e.target.checked)} />Include answered and skipped</label>
    {!questions.length && <p className="muted">No {showSaved ? "saved" : "open"} research questions yet.</p>}
    {questions.map(question => <BankCard key={question.id} question={question} snapshot={snapshot} busy={busy} onAnswer={onAnswer} onSource={onSource} />)}
    {research.graphProposals.length > 0 && <details open><summary>Proposed family connections ({research.graphProposals.filter(p => p.status === "pending").length} pending)</summary>{research.graphProposals.map(proposal => <article className="bank-card" key={proposal.id}><span className="badge">{proposal.status}</span><h4>{proposal.summary}</h4><p>{proposal.people.map(p => p.displayNameEn).join(", ")}</p>{proposal.relationships.map(r => <p key={r.id}>{proposal.people.find(p => p.id === r.fromPersonId)?.displayNameEn || snapshot.people.find(p => p.id === r.fromPersonId)?.displayNameEn || r.fromPersonId} · {r.type} · {proposal.people.find(p => p.id === r.toPersonId)?.displayNameEn || snapshot.people.find(p => p.id === r.toPersonId)?.displayNameEn || r.toPersonId}</p>)}{proposal.alternatives.length > 0 && <details><summary>Alternative identities</summary>{proposal.alternatives.map(a => <p key={a.personId}>{snapshot.people.find(p => p.id === a.personId)?.displayNameEn || a.personId}: {a.reason}</p>)}</details>}<details><summary>Supporting evidence</summary>{proposal.support.map((s,i) => <blockquote key={i}>{s.quote}<button className="text-button" onClick={() => onSource(s.sourceId)}>{s.locator}</button></blockquote>)}</details>{proposal.status === "pending" && <div className="bank-actions">{(["accept", "reject", "unknown"] as const).map(action => <button key={action} disabled={busy || !onReview} onClick={() => void onReview?.({proposalId: proposal.id, action, baseVersion: snapshot.version, requestId: crypto.randomUUID()})}>{action === "accept" ? "Accept connection" : action === "reject" ? "Reject" : "Keep unknown"}</button>)}</div>}</article>)}</details>}
  </section>;
}
function BankCard({question, snapshot, busy, onAnswer, onSource}: {question: BankQuestion; snapshot: ProjectSnapshot; busy: boolean; onAnswer?: (input: BankAnswerInput) => Promise<boolean>; onSource: (id: string) => void}) {
  const [editing, setEditing] = useState(false), [text, setText] = useState(""), [version, setVersion] = useState(snapshot.version);
  const round = snapshot.research!.cycles.find(c => c.id === question.cycleId)?.ordinal;
  const stale = editing && version !== snapshot.version;
  const save = async (action: BankAnswerInput["action"]) => {
    if (await onAnswer?.({questionId: question.id, action, ...(action === "correct" ? {text: text.trim()} : {}), baseVersion: action === "correct" ? version : snapshot.version, requestId: crypto.randomUUID()})) setEditing(false);
  };
  return <article className="bank-card"><small>{round ? `Round ${round} · ` : ""}{question.priority} · {question.status}</small><h4>{question.subject}</h4><p>{question.prompt}</p><p className="muted">{question.uncertainty}</p>
    <details><summary>Sources and possible people</summary>{question.support.map((span,i) => <blockquote key={i}>{span.quote}<button className="text-button" onClick={() => onSource(span.sourceId)}>{span.locator}</button></blockquote>)}{[...new Set([...question.personIds, ...question.candidatePersonIds])].map(id => <p key={id}>{snapshot.people.find(p => p.id === id)?.displayNameEn || "Unresolved person candidate"}</p>)}</details>
    {!!question.answers.length && <details><summary>Answer history ({question.answers.length})</summary>{question.answers.map((a,i) => <p key={i}>{a.action}: {a.text || (a.action === "unknown" ? "Kept unresolved" : a.action === "skip" ? "Saved for later" : "Confirmed")} · {new Date(a.savedAt).toLocaleString("en-US")}</p>)}</details>}
    {editing && <label className="field">Your answer<textarea value={text} onChange={e => setText(e.target.value)} rows={3} maxLength={4000} /></label>}
    {stale && <p className="stale-draft">New results arrived. Your answer is preserved. <button onClick={() => setVersion(snapshot.version)}>Use latest version</button></p>}
    {question.status !== "superseded" && <div className="bank-actions">{editing ? <><button disabled={busy || !onAnswer || !text.trim() || stale} onClick={() => void save("correct")}>Save answer</button><button onClick={() => setEditing(false)}>Cancel edit</button></> : <><button disabled={busy || !onAnswer} onClick={() => void save("confirm")}>Confirm</button><button disabled={busy || !onAnswer} onClick={() => {setEditing(true); setText(question.answers.at(-1)?.text || ""); setVersion(snapshot.version);}}>Answer or correct</button></>}<button disabled={busy || !onAnswer} onClick={() => void save("unknown")}>I don't know</button><button disabled={busy || !onAnswer} onClick={() => void save("skip")}>Skip for now</button></div>}
  </article>;
}
