/** Fictional UI states only. No live sources, model requests, OAuth or book generation. */
import {useState} from "react";
import {createRoot} from "react-dom/client";
import {RootsApp} from "../../src/ui";
import {InputScreen} from "../../src/ui/InputScreen";
import {syntheticSnapshot} from "../../packages/contracts/fixtures";
import {Round3StateSchema, RunStateSchema, ResearchJobSchema, ResearchCycleSchema, MetricTotalsSchema, type RootsApi, type ProjectSnapshot, type ConnectionStatus} from "../../packages/contracts";
const at = () => new Date().toISOString(), hash = "a".repeat(64), storage = "roots-round3-fictional-ui";
const image = (id: string, enhanced = false) => "data:image/svg+xml," + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="${id === 'portrait' ? 480 : 800}" height="${id === 'portrait' ? 640 : 480}"><rect width="100%" height="100%" fill="${enhanced ? '#9caf8b' : id === 'modern' ? '#c7d6e3' : '#c7b798'}"/><rect x="40" y="80" width="180" height="220" rx="60" fill="#736c5d"/><circle cx="130" cy="120" r="40" fill="#dbccb4"/><text x="22" y="35" font-size="22">FICTIONAL ${id.toUpperCase()} ${enhanced ? 'ENHANCED' : 'ORIGINAL'}</text></svg>`);
const support = [{sourceId:"fixture-source", locator:"line 1", quote:"Fictional test evidence only."}];
function fresh(): ProjectSnapshot {
  const s = structuredClone(syntheticSnapshot);
  s.projectId = "round3-fictional-ui"; s.version = 1; s.input = {...s.input, seedName:"Fictional Alex", researchMode:"round3"};
  s.sources = [{...s.sources[0], id:"fixture-source", originalText:support[0].quote, title:"Fictional source", originalLocator:"fictional.txt"}];
  s.people = s.people.map((p,i) => ({...p, displayNameEn:`Fictional Person ${i+1}`, photoIds: i === 0 ? ["modern", "portrait", "group"] : []}));
  s.assets = ["modern", "portrait", "group", "portrait-enhanced", "group-enhanced"].map(id => ({id, sourceId:"fixture-source", originalName:`${id}.svg`, mediaType:"image/svg+xml", byteLength:400, storageKey:"fixture", contentHash:id}));
  s.photoAnnotations = ["modern", "portrait", "group"].map(assetId => ({assetId,file:`${assetId}.svg`,positions:[],depictedPersonIds:[s.people[0].id],caption:`Fictional ${assetId} evidence. Identity remains unreviewed.`, support}));
  s.researchEvents=[]; s.claims=[]; s.proposals=[]; s.stories=[]; s.history=[]; s.bookPassages=[]; s.files=[];
  const questions = Array.from({length:6},(_,i) => ({id:`q${i}`, category:i<3?"photo":i===3?"origin":i===4?"recollection":"conflict", prompt:`Fictional check ${i+1}: ${i<3?['modern family photograph','old portrait','old group scene'][i]:'review the supplied clue'}`, recommendation:i===5?"The date is uncertain.":"Fictional source-backed recommendation.",support,personIds:[s.people[0].id],effect:{kind:"annotation",photoAssetId:["modern","portrait","group"][i]},status:"ready",origin:i===4?"live":"prepared",requiresAstra:i===4}));
  s.run = RunStateSchema.parse({runId:"fixture-run",startedAt:at(),phase:"questions",nextSequence:1,packetVersion:"fictional",packetHash:hash,language:"en",questions,answers:[],batches:[],initialBranchIds:[],targetPeople:5,modelStatus:"completed",book:{status:"empty"}});
  const totals = MetricTotalsSchema.parse(Object.fromEntries(Object.keys(MetricTotalsSchema.shape).map(key=>[key,0])));
  Object.assign(totals,{people:5,sourcesSelected:4,sourcesProcessed:4,documentsRead:1,photosReceived:3,photosIndexed:3,oldPhotosSelected:2,enhancedPhotosReady:2});
  s.research = Round3StateSchema.parse({schemaVersion:"roots-research-v3",packetVersion:"fictional",packetHash:hash,intake:{id:"fixture-intake",status:"questions",startedAt:at(),inputFingerprint:hash,questionIds:questions.map(q=>q.id),jobIds:[]},oldPhotoAssetIds:["portrait","group"],photoPairQA:["portrait","group"].map(id=>({id:`pair-${id}`,personIds:[s.people[0].id],originalAssetId:id,originalHash:hash,enhancedAssetId:`${id}-enhanced`,enhancedHash:hash,origin:"prepared",method:"Code-generated fixture for UI only",caption:`Fictional ${id} comparison`,alignment:{mode:"aligned"},evidenceRootId:"fictional",preparedAt:at(),qa:{status:"passed",notes:"Fictional UI state only"}})),metrics:{asOfVersion:1,totals,cycles:[]}});
  s.photoPairs = s.research.photoPairQA;
  return s;
}
let current = fresh();
try {const saved=localStorage.getItem(storage); if(saved) current=JSON.parse(saved);} catch {}
let missing = false;
const save = () => {current.version++; localStorage.setItem(storage,JSON.stringify(current)); return structuredClone(current);};
let statuses: ConnectionStatus[] = ["drive","gmail"].map(provider=>({provider:provider as "drive"|"gmail",mode:"live",status:"disconnected",selectedScope:[],configured:false}));
const unavailable=async()=>{throw new Error("Fictional UI harness: use the real API for this action.");};
const api:RootsApi={
  getSnapshot:async()=>structuredClone(current),createProject:async(input)=>{current=fresh();current.input=input;return save();},
  answerSetupQuestion:async(_id,input)=>{current.run!.answers=current.run!.answers.filter(a=>a.questionId!==input.questionId);current.run!.answers.push({...input,savedAt:at(),originalRecommendation:"Fixture",savedText:input.text||input.action,sourceIds:["fixture-source"]});if(current.run!.answers.length===6)current.research!.intake.status="ready";return save();},
  researchCycle:async(_id,input)=>{const r=current.research!;const existing=r.cycles.find(c=>c.id===input.cycleId);if(existing){existing.status=input.action==="pause"?"paused":input.action==="cancel"?"cancelled":"running";r.jobs.filter(j=>j.cycleId===existing.id).forEach(j=>j.status=existing.status==="running"?"running":existing.status==="cancelled"?"cancelled":"paused");}else{const ordinal=r.cycles.length+1,id=`cycle-${ordinal}`;const cycle=ResearchCycleSchema.parse({id,ordinal,kind:input.action,requestId:input.requestId,inputFingerprint:hash,status:"running",createdAt:at(),plan:{id:`plan-${ordinal}`,cycleId:id,objectives:["Inspect the selected fictional record","Compare the unresolved date"],sourceIds:["fixture-source"],queries:[],createdAt:at(),model:"Fictional UI fixture",origin:"prepared"}});r.cycles.push(cycle);r.jobs.push(ResearchJobSchema.parse({id:`job-${ordinal}`,cycleId:id,stage:"research",kind:"analyze",tool:"Fictional fixture",objective:`Inspect fictional record for round ${ordinal}`,sourceIds:["fixture-source"],status:"running",startedAt:at(),inputFingerprint:hash,origin:"prepared"}));}return save();},
  answerBankQuestion:async(_id,input)=>{const q=current.research!.questionBank.find(q=>q.id===input.questionId)!;q.answers.push({...input,savedAt:at()});q.status=input.action==="skip"?"skipped":input.action==="unknown"?"open":"answered";return save();},
  autofillFamilyDetails:async()=>({id:"fixture-autofill",createdAt:at(),inputFingerprint:hash,appliedPaths:[],fields:[{path:"self.fullName",value:"Fictional Alex",support,conflicts:[]},{path:"self.birthPlace",value:"Fictional Harbor",support,conflicts:[]},{path:"father.fullName",value:"Fictional Morgan",support,conflicts:[]},{path:"mother.birthYear",value:"1940",support,conflicts:["1941"]}]}),
  getConnections:async()=>structuredClone(statuses),
  addContribution:unavailable,reviewProposal:unavailable,mutateGraph:unavailable,downloadFamilyBook:unavailable,
  assetUrl:(_id,asset)=>missing&&asset.endsWith("enhanced")?"/deliberately-missing.svg":image(asset.replace("-enhanced",""),asset.endsWith("enhanced")),
};
function Harness(){const[mode,setMode]=useState("workspace"),[key,setKey]=useState(0);return <><aside style={{padding:12,background:"#ffe7ae"}}><strong>FICTIONAL UI QA ONLY. No actual research, OAuth or private-photo validation.</strong><div>{["workspace","intake"].map(m=><button key={m} onClick={()=>setMode(m)}>{m}</button>)}<button onClick={()=>{current=fresh();save();setKey(k=>k+1);}}>Reset fixture</button><button onClick={()=>{const c=current.research!.cycles.at(-1);if(!c)return;c.status="completed";c.completedAt=at();current.research!.jobs.filter(j=>j.cycleId===c.id).forEach(j=>{j.status=c.ordinal===3?"no_match":"completed";j.completedAt=at();j.summary=c.ordinal===3?"No matching record in the selected source.":"Fictional result saved.";});current.research!.questionBank.push({id:`bank-${c.ordinal}`,cycleId:c.id,subject:"A later fictional clue",prompt:"Is this recorded year correct?",uncertainty:"Two fictional dates disagree.",support,personIds:[],candidatePersonIds:[],priority:"later",status:"open",answers:[],createdAt:at()});save();setKey(k=>k+1);}}>Finish fixture round</button><button onClick={()=>{missing=!missing;setKey(k=>k+1);}}>Toggle missing derivative</button><button onClick={()=>{statuses=statuses.map(s=>({...s,status:"expired",accountDisplay:"fictional@example.test",error:"Fictional expired connection"}));setKey(k=>k+1);}}>Expired providers</button></div></aside>{mode==="intake"?<InputScreen key={key} api={api} busy={false} error={null} onStart={()=>setMode("workspace")}/>:<RootsApp key={key} api={api} initialProjectId="round3-fictional-ui" mode="replay"/>}</>;}
createRoot(document.getElementById("root")!).render(<div className="roots-app"><Harness/></div>);
