import {randomBytes,createHash} from 'node:crypto';
import {mkdir,readFile,writeFile,rename,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {ProviderSchema, type ConnectionStatus, type InputFile, UPLOAD_LIMITS} from '../../packages/contracts';
import {dataRoot} from '../state/store';
import {AppError} from '../state/validation';
type Provider='drive'|'gmail';
type Token={access_token:string;refresh_token?:string;expiresAt:number;scope:string;status:ConnectionStatus};
const scopes={drive:'https://www.googleapis.com/auth/drive.readonly',gmail:'https://www.googleapis.com/auth/gmail.readonly'};
const dir=()=>join(dataRoot(),'_connections');
const demoMode=()=>process.env.ROOTS_DEMO_CONNECTIONS==='true';
const configured=()=>!!(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET);
const callback=()=>process.env.GOOGLE_REDIRECT_URI||'http://127.0.0.1:3300/api/connections/callback';
const safeId=(v:string)=>{if(!/^[A-Za-z0-9_-]{1,300}$/.test(v))throw new AppError('Invalid selected Google item ID.');return v;};
async function save(name:string,value:unknown){await mkdir(dir(),{recursive:true,mode:0o700});const temp=join(dir(),`${name}.${randomBytes(8).toString('hex')}.tmp`);await writeFile(temp,JSON.stringify(value),{mode:0o600});await rename(temp,join(dir(),`${name}.json`));}
async function read<T>(name:string):Promise<T|undefined>{try{return JSON.parse(await readFile(join(dir(),`${name}.json`),'utf8'));}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return undefined;throw e;}}
async function token(provider:Provider){const t=await read<Token>(provider);if(!t)throw new AppError('Connect this Google account first.',401,'CONNECTION_REQUIRED');if(t.expiresAt>Date.now()+30000)return t;if(!t.refresh_token){t.status.status='expired';await save(provider,t);throw new AppError('Google authorization expired. Reconnect the account.',401,'CONNECTION_EXPIRED');}const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:t.refresh_token,grant_type:'refresh_token'}),signal:AbortSignal.timeout(15000)});if(!r.ok){t.status.status='expired';await save(provider,t);throw new AppError('Google authorization expired. Reconnect the account.',401,'CONNECTION_EXPIRED');}const fresh=await r.json();t.access_token=fresh.access_token;t.expiresAt=Date.now()+fresh.expires_in*1000;await save(provider,t);return t;}
async function google(provider:Provider,path:string){const t=await token(provider);const r=await fetch(`https://www.googleapis.com/${path}`,{headers:{Authorization:`Bearer ${t.access_token}`},signal:AbortSignal.timeout(20000),redirect:'error'});if(!r.ok){t.status.status=r.status===401?'expired':'error';t.status.error=`Google read failed (HTTP ${r.status}).`;await save(provider,t);throw new AppError(t.status.error,r.status===401?401:502,'GOOGLE_READ_FAILED');}return r;}
export async function connectionStatuses():Promise<ConnectionStatus[]>{return Promise.all((['drive','gmail'] as const).map(async provider=>{const t=await read<Token>(provider);if(demoMode()){const demo=await read<{connected:boolean}>(`demo-${provider}`);return {provider,mode:'demo' as const,status:demo?.connected?'connected' as const:'disconnected' as const,accountDisplay:'Demo: prepared local copies',selectedScope:[],configured:true};}return {...(t?.status||{provider,mode:'live' as const,status:'disconnected',selectedScope:[]}),configured:configured(),...(t&&t.expiresAt<Date.now()&&!t.refresh_token?{status:'expired' as const}:{})};}));}
export async function beginConnection(raw:string){const provider=ProviderSchema.parse(raw);if(demoMode()){await save(`demo-${provider}`,{connected:true});return {url:`/?connection=demo&provider=${provider}`,state:''};}if(!configured())throw new AppError('Configure GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in the local server environment.',503,'GOOGLE_NOT_CONFIGURED');const state=randomBytes(32).toString('hex'),verifier=randomBytes(48).toString('base64url');await save(`oauth-${state}`,{provider,verifier,expiresAt:Date.now()+10*60*1000});const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID!,redirect_uri:callback(),response_type:'code',scope:scopes[provider],state,access_type:'offline',prompt:'consent',code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256'}).toString();return {url:url.href,state};}
export async function finishConnection(code:string,state:string,cookie:string){if(!/^[a-f0-9]{64}$/.test(state)||cookie!==state)throw new AppError('OAuth state did not match this browser.',403,'OAUTH_STATE');const pending=await read<{provider:Provider;verifier:string;expiresAt:number}>(`oauth-${state}`);if(!pending||pending.expiresAt<Date.now())throw new AppError('OAuth request expired.',403,'OAUTH_EXPIRED');await rm(join(dir(),`oauth-${state}.json`));const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID!,client_secret:process.env.GOOGLE_CLIENT_SECRET!,redirect_uri:callback(),grant_type:'authorization_code',code_verifier:pending.verifier}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw new AppError('Google authorization exchange failed. Try connecting again.',502,'OAUTH_EXCHANGE');const t=await r.json();if(typeof t.access_token!=='string'||!String(t.scope||'').split(' ').includes(scopes[pending.provider]))throw new AppError('Required read-only scope was not granted.',403,'OAUTH_SCOPE');await save(pending.provider,{access_token:t.access_token,refresh_token:t.refresh_token,scope:t.scope,expiresAt:Date.now()+t.expires_in*1000,status:{provider:pending.provider,connectionId:randomBytes(16).toString('hex'),status:'connecting',configured:true,selectedScope:[]}});return verifyConnection(pending.provider,[]);}
export async function verifyConnection(raw:string,selection:string[]=[]):Promise<ConnectionStatus>{const provider=ProviderSchema.parse(raw);if(demoMode())return (await connectionStatuses()).find(x=>x.provider===provider)!;selection.forEach(safeId);if(selection.length>40)throw new AppError('Select at most 40 source IDs.');const t=await token(provider);let accountDisplay:string;if(provider==='gmail'){const profile=await(await google(provider,'gmail/v1/users/me/profile')).json();accountDisplay=profile.emailAddress;if(selection.length)await google(provider,`gmail/v1/users/me/messages/${selection[0]}?format=metadata`);else await google(provider,'gmail/v1/users/me/messages?maxResults=1');}else{const about=await(await google(provider,'drive/v3/about?fields=user')).json();accountDisplay=about.user.emailAddress;if(selection.length)await google(provider,`drive/v3/files/${selection[0]}?fields=id,name,mimeType`);else await google(provider,'drive/v3/files?pageSize=1&fields=files(id,name)');}t.status={...t.status,provider,mode:'live',configured:true,status:'connected',accountDisplay,verifiedAt:new Date().toISOString(),selectedScope:selection};delete t.status.error;await save(provider,t);return t.status;}
export async function disconnectConnection(raw:string):Promise<ConnectionStatus>{const provider=ProviderSchema.parse(raw);if(demoMode()){await save(`demo-${provider}`,{connected:false});return {provider,mode:'demo',status:'disconnected',configured:true,selectedScope:[]};}await rm(join(dir(),`${provider}.json`),{force:true});return {provider,mode:'live',status:'disconnected',configured:configured(),selectedScope:[]};}
async function boundedBytes(response:Response){if(Number(response.headers.get('content-length')||0)>UPLOAD_LIMITS.maxFileBytes)throw new AppError('Selected Google file exceeds the 25 MB limit.',413);const reader=response.body!.getReader(),parts:Uint8Array[]=[];let n=0;try{while(true){const {done,value}=await reader.read();if(done)break;n+=value.length;if(n>UPLOAD_LIMITS.maxFileBytes){await reader.cancel();throw new AppError('Selected Google file exceeds the 25 MB limit.',413);}parts.push(value);}}finally{reader.releaseLock();}return Buffer.concat(parts);}
export async function readSelectedSources(raw:string,selectedIds:string[]):Promise<InputFile[]>{const provider=ProviderSchema.parse(raw);if(!selectedIds.length||selectedIds.length>40)throw new AppError('Choose between 1 and 40 selected source IDs.');selectedIds.forEach(safeId);const files:InputFile[]=[];let total=0;const add=(id:string,name:string,mediaType:string,bytes:Uint8Array)=>{total+=bytes.length;if(files.length>=40||total>UPLOAD_LIMITS.maxTotalBytes)throw new AppError('Selected Google sources exceed the import limit.',413);files.push({uploadId:`${provider}-${id}`,originalName:name.replace(/[\\/]/g,'_'),mediaType,bytes});};for(const id of [...new Set(selectedIds)]){if(provider==='gmail'){const message=await(await google(provider,`gmail/v1/users/me/messages/${id}?format=full`)).json();const headers=message.payload?.headers||[];const h=(name:string)=>headers.find((x:{name:string})=>x.name.toLowerCase()===name)?.value||'';const parts=(p:any):string[]=>[...(p.mimeType==='text/plain'&&p.body?.data?[Buffer.from(p.body.data,'base64url').toString('utf8')]:[]),...(p.parts||[]).flatMap(parts)];const body=parts(message.payload).join('\n');if(!body.trim())throw new AppError('Selected correspondence has no supported plain-text body.',422,'NO_TEXT');add(id,`Correspondence-${id}.txt`,'text/plain',Buffer.from(`From: ${h('from')}\nDate: ${h('date')}\nSubject: ${h('subject')}\n\n${body}`));}else{const meta=await(await google(provider,`drive/v3/files/${id}?fields=id,name,mimeType,size`)).json();if(meta.mimeType==='application/vnd.google-apps.folder'){const listing=await(await google(provider,`drive/v3/files?q=${encodeURIComponent(`'${id}' in parents and trashed = false`)}&pageSize=40&fields=files(id,name,mimeType),nextPageToken`)).json();if(listing.nextPageToken)throw new AppError('Folder contains more than 40 files. Select specific files.',413);const children=listing.files.filter((f:any)=>f.mimeType!=='application/vnd.google-apps.folder').map((f:any)=>f.id);const nested=children.length?await readSelectedSources('drive',children):[];for(const f of nested)add(f.uploadId.replace('drive-',''),f.originalName,f.mediaType,f.bytes);continue;}const native=meta.mimeType==='application/vnd.google-apps.document';if(meta.mimeType.startsWith('application/vnd.google-apps.')&&!native)throw new AppError('Select ordinary files or Google Docs for this importer.',422);const response=await google(provider,native?`drive/v3/files/${id}/export?mimeType=text%2Fplain`:`drive/v3/files/${id}?alt=media`);add(id,native?`${meta.name}.txt`:meta.name,native?'text/plain':meta.mimeType,await boundedBytes(response));}}await verifyConnection(provider,selectedIds);return files;}
