import {randomUUID,createHash} from 'node:crypto';
import {mkdir,readFile,writeFile,rename} from 'node:fs/promises';
import {join} from 'node:path';
import {type ProjectSnapshot,type BookEdition} from '../../packages/contracts';
import {dataRoot,loadProject,updateProject,readAsset} from '../state/store';
import {researchFingerprint,digest} from '../state/research';
import {AppError} from '../state/validation';
import {generatePassage} from './astra';
import {dataModules} from './data-modules';
import {readGeneratedZip} from './bundle';
const tasks=new Map<string,Promise<ProjectSnapshot>>();
const bytesHash=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex');
const path=(id:string,key:string,kind:string)=>join(dataRoot(),id,'editions',`${key}.${kind}`);
const now=()=>new Date().toISOString();
export async function prepareEdition(id:string){if(tasks.has(id))return tasks.get(id)!;const task=buildEdition(id).finally(()=>tasks.delete(id));tasks.set(id,task);return task;}
async function buildEdition(id:string){let s=await loadProject(id);if(!s.research?.bookPlan)throw new AppError('The source-backed English book plan is not prepared.',409,'BOOK_PLAN_REQUIRED');if(!s.people.length)throw new AppError('Start research before preparing the book.',409);const key=researchFingerprint(s);if(s.research.bookEdition?.fingerprint===key&&['current','sealed'].includes(s.research.bookEdition.status))return s;
 const missing=s.research.oldPhotoAssetIds.filter(id=>!s.research!.photoPairQA.some(p=>p.originalAssetId===id&&p.qa.status==='passed'&&p.alignment.mode==='aligned'));
 if(missing.length)throw new AppError(`${missing.length} selected old photographs still need a validated comparison.`,409,'PHOTO_PAIRS_INCOMPLETE');
 const edition:BookEdition={id:`edition-${randomUUID()}`,fingerprint:key,status:'preparing',stateVersion:s.version,pageCount:0,createdAt:now(),previousEditionId:s.research.bookEdition?.id,chapterFingerprints:Object.fromEntries(s.research.bookPlan.chapters.map(ch=>[ch.id,digest([ch.fingerprint,ch.claimIds.map(id=>s.claims.find(c=>c.id===id)),s.run?.answers,s.research?.questionBank])]))};
 await updateProject(id,p=>{if(p.research!.bookEdition?.status==='sealed')p.research!.previousEditions.push(p.research!.bookEdition);p.research!.bookEdition=edition;p.run!.book={status:'preparing',key};p.bookStatus='generating';});
 try{let passages=s.bookPassages;if(s.stories.some(st=>st.status==='accepted'))passages=[await generatePassage(s)];else{const claim=s.claims.find(c=>c.status==='accepted');if(!claim)throw new AppError('Review a documented family record first.',409);passages=[{id:`passage-${randomUUID()}`,text:`Supplied family record: ${claim.value}`,claimIds:[claim.id],sourceIds:claim.sourceIds,sourceLocators:claim.spans,acceptedStateVersion:s.version,origin:'prepared'}];}
 s=await updateProject(id,p=>{if(researchFingerprint(p)!==key)throw new AppError('The family changed while preparing this edition.',409,'STALE_EDITION');p.bookPassages=passages.map(x=>({...x,acceptedStateVersion:p.version+1}));p.bookStatus='current';});
 const bundle=await dataModules.buildFamilyBundle({snapshot:s,passages:s.bookPassages,resolveAsset:assetId=>readAsset(id,assetId)});const entries=readGeneratedZip(bundle.bytes),pdf=entries.get('book.pdf')!,html=entries.get('book.html')!;const pageCount=(pdf.toString('latin1').match(/\/Type\s*\/Page\b/g)||[]).length;if(pageCount<35||pageCount>40)throw new AppError(`The prepared book has ${pageCount} pages; this edition requires 35-40.`,409,'BOOK_PAGE_RANGE');
 await mkdir(join(dataRoot(),id,'editions'),{recursive:true,mode:0o700});for(const [kind,bytes]of [['pdf',pdf],['html',html],['zip',bundle.bytes]] as const){const dest=path(id,key,kind),tmp=`${dest}.${randomUUID()}.tmp`;await writeFile(tmp,bytes,{mode:0o600});await rename(tmp,dest);}
 return updateProject(id,p=>{if(researchFingerprint(p)!==key)throw new AppError('The family changed before this edition was ready.',409,'STALE_EDITION');p.research!.bookEdition={...edition,status:'current',pageCount,preparedAt:now(),stateVersion:p.version+1,pdfHash:bytesHash(pdf),zipHash:bytesHash(bundle.bytes)};p.run!.book={status:'ready',key,preparedAt:now(),stateVersion:p.version+1};p.run!.phase='ready';});
 }catch(error){await updateProject(id,p=>{if(p.research!.bookEdition?.fingerprint!==key)return false;p.research!.bookEdition.status='error';p.research!.bookEdition.error=error instanceof AppError?error.message:'Book preparation failed. Retry is available.';p.bookStatus='failed';p.run!.book={status:'failed',error:p.research!.bookEdition.error};});throw error;}
}
export async function previewEdition(id:string){const s=await loadProject(id),e=s.research?.bookEdition;if(!e||!['current','sealed'].includes(e.status)||e.fingerprint!==researchFingerprint(s))throw new AppError('Prepare the current full book before previewing.',409,'STALE_EDITION');const bytes=await readFile(path(id,e.fingerprint,'pdf'));if(bytesHash(bytes)!==e.pdfHash)throw new AppError('Book integrity check failed.',409);return bytes;}
export async function downloadEdition(id:string){let s=await loadProject(id);if(!s.research?.bookEdition||s.research.bookEdition.fingerprint!==researchFingerprint(s)||!['current','sealed'].includes(s.research.bookEdition.status))s=await prepareEdition(id);const e=s.research!.bookEdition!,bytes=await readFile(path(id,e.fingerprint,'zip'));if(bytesHash(bytes)!==e.zipHash)throw new AppError('Sealed download integrity check failed.',409);await updateProject(id,p=>{if(researchFingerprint(p)!==e.fingerprint)throw new AppError('The book changed. Download the current edition.',409);p.research!.bookEdition!.status='sealed';p.research!.bookEdition!.sealedAt ||=now();for(const cycle of p.research!.cycles)if(['queued','running','paused'].includes(cycle.status)){cycle.status='cancelled';cycle.completedAt=now();for(const job of p.research!.jobs.filter(j=>j.cycleId===cycle.id&&['queued','running','paused'].includes(j.status))){job.status='cancelled';delete job.leaseToken;delete job.leaseUntil;}}},{isReplay:p=>p.research?.bookEdition?.id===e.id&&p.research.bookEdition.status==='sealed'});return {bytes,filename:`Osmy-Roots-${e.id}.zip`};}
